"""Build two fast subsets from the same Noto Sans SC variable font (fontTools)."""
from pathlib import Path
from fontTools import subset
from fontTools.ttLib import TTFont

web = Path(__file__).resolve().parents[1]
source = web / 'public/fonts/noto-sans-sc.woff2'
available = set(TTFont(source).getBestCmap())
latin = {n for n in available if n <= 0x024F or 0x2000 <= n <= 0x206F or 0x20A0 <= n <= 0x20CF}
text = ''.join(p.read_text() for folder in [web/'app', web/'components', web/'lib', web.parents[1]/'packages/shared/src'] for p in folder.rglob('*.ts*'))
ui = {ord(c) for c in text} & available - latin
rules = ["@font-face{font-family:'Loop Sans';src:url('/fonts/noto-sans-sc.woff2') format('woff2');font-weight:100 900;font-style:normal;font-display:swap}"]
for label, points in [('ui', ui), ('latin', latin)]:
    font = TTFont(source)
    options = subset.Options(); options.flavor = 'woff2'; options.layout_features = ['*']
    job = subset.Subsetter(options=options); job.populate(unicodes=points); job.subset(font)
    font.flavor = 'woff2'; filename = f'loop-sans-{label}.woff2'; font.save(web/'public/fonts'/filename)
    ranges = ','.join(f'U+{n:X}' for n in sorted(points))
    rules.append(f"@font-face{{font-family:'Loop Sans';src:url('/fonts/{filename}') format('woff2');font-weight:100 900;font-style:normal;font-display:swap;unicode-range:{ranges}}}")
(web/'app/fonts.css').write_text('/* Generated by scripts/build-fonts.py. One family, language subsets. */\n'+'\n'.join(rules)+'\n')
