import type { Metadata } from 'next';
import Link from 'next/link';
import { JournalFigure } from '../../../components/journal-example';
import { notFound } from 'next/navigation';
import { JsonLd } from '../../../components/json-ld';
import { SiteFooter } from '../../../components/site-footer';
import { SiteHeader } from '../../../components/site-header';
import { articles, getArticle } from '../../../lib/articles';
import { pageMetadata, site } from '../../../lib/seo';

const content: Record<string, { heading: string; intro: string; sections: [string, string, string][] }> = {
  'why-recall-beats-rereading': { heading: 'Recall changes the work your memory has to do', intro: 'Rereading shows the answer while active recall asks the brain to reconstruct it. That difference turns a comfortable review into useful evidence about what you can retrieve without help.', sections: [
    ['Recognition feels persuasive', 'A sentence can look familiar because you saw it moments ago. Familiarity lowers the effort of reading, but it does not prove that the idea will be available tomorrow or in a different context.', 'Close the source and ask a specific question instead. The pause before an answer is diagnostic: immediate recall suggests a stable path, partial recall exposes a weak link, and silence tells you exactly what to revisit.'],
    ['Design useful difficulty', 'A good prompt is neither a giveaway nor a riddle. It contains enough context to identify one intended answer while withholding the answer itself. Ask for the smallest unit that still matters.', 'After answering, flip the card and compare rather than merely read. Put the correction first. Keep examples, distinctions, or sources in separate back tabs so they support the answer without competing with it.'],
    ['Turn evidence into the next loop', 'Rate the attempt honestly. “Clear” means the answer arrived accurately and quickly. “Fuzzy” means it emerged after effort or lacked precision. “Forgotten” means the path needs rebuilding.', 'These labels are not grades. They are routing instructions for future review. A short loop built from honest signals is more useful than a long session built from the pleasant feeling of recognition.'],
  ] },
  'make-a-card-worth-reviewing': { heading: 'A useful card makes one clear demand', intro: 'The quality of a flashcard is determined before the first review. A precise prompt produces interpretable recall; an overloaded prompt produces hesitation without showing which part of the knowledge is missing.', sections: [
    ['Start with one decision', 'Write the front so you can tell whether the response is right. Replace broad prompts such as “Explain photosynthesis” with smaller questions about inputs, outputs, location, or purpose.', 'Atomic does not mean trivial. One card can still test a relationship or distinction, but it should lead to one assessable response. Split lists when each item deserves an independent memory path.'],
    ['Keep the answer corrective', 'Place the shortest correct answer first on the back. Supporting detail should clarify a likely mistake, demonstrate usage, or show why the answer matters—not repeat the entire source.', 'LoopCard back tabs are useful for dimensions such as meaning, example, distinction, story, and source. The tabs preserve context while letting the learner reveal only the layer needed at that moment.'],
    ['Edit after a real review', 'Cards often reveal their defects in use. If two answers seem reasonable, add context to the prompt. If the answer is consistently recalled but a detail is missed, separate that detail into its own card.', 'Treat a deck as a working memory model rather than a finished document. Removing an ambiguous or low-value card can improve a review loop as much as adding a new one.'],
  ] },
  'small-loops-long-memory': { heading: 'Short review loops are easier to return to', intro: 'A memory practice succeeds through repeated retrieval, not one heroic session. Small loops lower the cost of beginning and make it easier to notice which cards deserve attention today.', sections: [
    ['Choose a finishable unit', 'A loop should have a visible end. Ten focused cards can be more useful than opening a deck of hundreds with no stopping point. Completion creates a clean record of what was clear, fuzzy, or forgotten.', 'Keep the session short enough that attention remains on recall rather than endurance. When the habit is reliable, frequency can grow naturally without turning every review into an appointment.'],
    ['Let difficulty change the route', 'Not every card needs equal exposure. A clear answer can wait; a fuzzy answer should return sooner; a forgotten answer may need a simpler prompt or additional context before repetition helps.', 'This adaptive rhythm protects time and keeps hard material visible. It also prevents familiar cards from filling the session simply because they are easy and pleasant to answer.'],
    ['Build a cue into ordinary life', 'Attach a loop to a stable moment: after coffee, before closing a laptop, or during a commute. The cue matters more than choosing an ambitious duration.', 'If a day is crowded, finish one small loop instead of abandoning the practice. Consistency preserves the path back to the material, and the review history shows where to resume.'],
  ] },
  'designing-the-back-of-a-card': { heading: 'The back should correct, not overwhelm', intro: 'A card back has one primary job: show the intended answer clearly enough to judge recall. Additional information earns a place only when it explains, distinguishes, or anchors that answer.', sections: [
    ['Lead with the answer', 'Use the strongest visual position for the concise answer. Do not begin by repeating the front or adding labels that the learner already saw. The first glance should resolve the retrieval attempt.', 'Typography and spacing should establish a clear order: answer, short explanation, then optional detail. If everything has equal emphasis, the learner has to search the card after already doing the work of recall.'],
    ['Reveal dimensions in tabs', 'Different card types need different supporting dimensions. A word may need meaning, example, and distinction. A formula may need name, structure, and use. A cultural saying may need answer, story, and source.', 'Horizontal tabs keep those dimensions available without stacking them into a long sheet. The current tab belongs at the lower left; secondary actions stay separate on the lower right so navigation and editing do not compete.'],
    ['Remove information that does not help', 'More context is not automatically more useful. Repeated prompt text, generic definitions, and unrelated facts increase reading time without improving the judgment of recall.', 'Test the back after answering aloud. If a block does not help you confirm, correct, or deepen that answer, move it to another card or remove it from the review surface.'],
  ] },
};

export async function generateStaticParams() { return articles.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const slug = (await params).slug; const article = getArticle(slug); if (!article) return {}; return pageMetadata({ title: `${article.title}: A Practical Guide`, description: `${article.excerpt} Learn the practical method, common mistakes, and a simple next step for better active-recall sessions with LoopCard.`, path: `/blog/${slug}` }); }

export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const slug = (await params).slug; const article = getArticle(slug); const body = content[slug]; if (!article || !body) notFound(); const current = articles.findIndex((item) => item.slug === slug); const next = articles[(current + 1) % articles.length];
  const jsonLd = { '@context': 'https://schema.org', '@type': 'BlogPosting', headline: article.title, description: article.excerpt, datePublished: article.isoDate, dateModified: article.isoDate, author: { '@type': 'Organization', name: 'LoopCard Studio', url: `${site.url}/about` }, publisher: { '@type': 'Organization', name: 'LoopCard Studio', logo: { '@type': 'ImageObject', url: `${site.url}/brand/loopcard-app-icon.png` } }, mainEntityOfPage: `${site.url}/blog/${slug}`, image: `${site.url}${site.ogImage}` };
  return <><SiteHeader /><main><section className="page-hero"><span className="eyebrow"><time dateTime={article.isoDate}>{article.date}</time></span><h1>{article.title}</h1><p>{body.intro}</p></section><article className="prose"><JournalFigure kind={current} /><p className="lead">{body.heading}.</p>{body.sections.map(([heading, first, second]) => <section key={heading}><h2>{heading}</h2><p>{first}</p><p>{second}</p></section>)}<aside className="article-next"><span className="eyebrow">Continue the practice</span><Link href={`/blog/${next.slug}`}>Next guide: {next.title} →</Link><Link href="/tools">Turn your notes into flashcards →</Link></aside></article></main><SiteFooter /><JsonLd data={jsonLd} /></>;
}
